Add empty bodies for added CPU API funtions
MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap pull request #17
Opened 2024-08-31 19:55 UTC by huwzpf

2024-09-03 13:18 UTC, MAJ0RRR approved these changes

2024-09-04 20:55 UTC, Kepins commented on cudampilib/include/cudampicommon.h
> +cudaError_t __cudampi__getCpuFreeThreads(int* count)
missing semicolon

2024-09-04 21:43 UTC, Kepins requested changes

2024-09-04 21:43 UTC, Kepins commented on cudampilib/include/cudampicommon.h
> +cudaError_t __cudampi__getCpuFreeThreads(int* count)
missing semicolon

2024-09-04 21:43 UTC, Kepins commented on cudampilib/include/cudampicommon.h
> +#include <cuda_runtime.h>
I believe if we want to include `<cuda_runtime.h>` in this file we need to modify our `compile` script to include this on line 13:
`gcc -c cudampicommon.c -Iinclude -o $BUILD_DIR/cudampicommon.o -I/usr/local/cuda/include`

2024-09-04 21:43 UTC, Kepins commented on cudampilib/cudampilib.c
> +void cpukernel(void *devPtr, int num_threads);
This function declaration should come from `apps/APPLICATION_NAME/appcpukernel` or similar. Maybe we should include empty definition for each cpu kernel (for each app) so there would be no errors:

```
/usr/bin/ld: build/cudampilib.o: in function `__cudampi__cpuKernel':
cudampilib.c:(.text+0x3337): undefined reference to `cpukernel'
```
during compilation of any app.

2024-09-04 21:43 UTC, Kepins commented on cudampilib/cudampilib.c
> +}
Include TODO with appropriate comment so we don't miss it later on or remove this function all together.

2024-09-04 21:43 UTC, Kepins commented on cudampilib/cudampilib.c
> +    // wyjebać local cpu
There is a possibility we will be showing this code to Czarnul. xD

2024-09-04 21:43 UTC, Kepins commented on cudampilib/cudampilib.c
>  #define  __cudampi_isLocalGpu __cudampi__currentDevice < __cudampi__GPUcountspernode[0]
nit. Two spaces after `#define`

2024-09-04 21:43 UTC, Kepins commented on cudampilib/cudampilib.c
> +}
We have such define for checking if isLocalGpu.
`#define  __cudampi_isLocalGpu __cudampi__currentDevice < __cudampi__GPUcountspernode[0]`
Couldn't this functionality also be a define?

2024-09-04 21:43 UTC, Kepins commented on cudampilib/cudampilib.c
> +  if (__cudampi__isLocalCpu) { // run locally
`__cudampi__isLocalCpu` is not defined maybe at least add it TODO?

2024-09-05 06:39 UTC, huwzpf commented on cudampilib/include/cudampicommon.h
> +#include <cuda_runtime.h>
Compilation will be fixed in #13.

2024-09-05 06:40 UTC, huwzpf commented on cudampilib/cudampilib.c
> +void cpukernel(void *devPtr, int num_threads);
The function will be defined in collatz app (and compilation of other apps disabled) in #13

2024-09-05 06:52 UTC, huwzpf commented on cudampilib/cudampilib.c
> +  if (__cudampi__isLocalCpu) { // run locally
As discussed, we won't use local CPUs. It should be removed.

2024-09-05 19:19 UTC, merged