Implement asynchronous cudaMemcpyAsync on slaves using cpu task mechanism
MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap pull request #65
Opened 2024-10-17 19:45 UTC by huwzpf

2024-10-17 20:03 UTC, Kepins approved these changes
LGTM :)

2024-10-19 22:00 UTC, MAJ0RRR commented on cudampilib/cudampilib.c
> +    *((int *)(sdata + sizeof(void *) + sizeof(unsigned long) + sizeof(cudaStream_t))) = counter;
Can't it be expressed simpler?

2024-10-19 22:02 UTC, MAJ0RRR commented on cudampilib/cudampislave.c
> +        gpu_host_to_device_args_t* args = malloc(sizeof(gpu_host_to_device_args_t));
Please check if malloc succeed.

2024-10-19 22:03 UTC, MAJ0RRR requested changes
Especially malloc.

2024-10-23 08:53 UTC, huwzpf commented on cudampilib/cudampilib.c
> +    *((int *)(sdata + sizeof(void *) + sizeof(unsigned long) + sizeof(cudaStream_t))) = counter;
What do you mean ? I think it clearly inidates that structure of `sdata` is `[void *, unsigned long, cudaStream_t, int]`

2024-10-24 19:26 UTC, MAJ0RRR commented on cudampilib/cudampilib.c
> +    *((int *)(sdata + sizeof(void *) + sizeof(unsigned long) + sizeof(cudaStream_t))) = counter;
ok, let it be

2024-10-24 19:30 UTC, MAJ0RRR commented on cudampilib/cudampilib.c
> +  int counter = getMsgCounter();
Can getMsgCounter fail somehow and what could happen if it did?

2024-10-24 19:33 UTC, MAJ0RRR commented on cudampilib/cudampislave.c
> +  allocatedGpuMemcpyBuffer buffer;
Was it intentional to copy it instead of using pointer for buffer?

2024-10-24 19:33 UTC, MAJ0RRR commented on cudampilib/cudampislave.c
> +  allocatedGpuMemcpyBuffer buffer;
^ same

2024-10-24 19:34 UTC, MAJ0RRR commented on cudampilib/cudampislave.c
> +    global->allocatedCount += 1;
Maybe add check for overflow?

2024-10-24 19:37 UTC, MAJ0RRR approved these changes
Most new functions are void type, maybe some of them could use error codes as a return value so we can easier debug if something breaks.

2024-10-24 19:46 UTC, huwzpf commented on cudampilib/cudampislave.c
> +    global->allocatedCount += 1;
Makes sense, but I think I could just switch type to unisgned long long, then rather malloc would fail than overflow of this varaible happen as it would need 18,446,744,073,709,551,615 buffers to be allocated

2024-10-24 19:50 UTC, huwzpf commented on cudampilib/cudampilib.c
> +  int counter = getMsgCounter();
I don't think it can fail. When counter reaches maximum value it just goes right back to minimum value. It operates under assumption that at most  32000 messages would be pending completion at once, which I believe is a safe margin. Also working around this unlikely scenario of having more than 32K messages pending at once might be pretty hard so I'd rather leave it as is.

2024-10-24 19:51 UTC, huwzpf commented on cudampilib/cudampislave.c
> +  allocatedGpuMemcpyBuffer buffer;
It's a structure that contains pointer to buffer. A structure could be as well embedded into args structure but I wanted to make it resuable.

2024-10-24 19:57 UTC, huwzpf commented
> Most new functions are void type, maybe some of them could use error codes as a return value so we can easier debug if something breaks.

All the functions print error logs necessary for debugging if something breaks. Although looking back at this code I believe they should not continue execution in case of error as something like allocation error means that application will evntually fail anyway, just at unexpected moment. I believe the best way to mitigate this would be to just exit at error so I added new Issue for implementing such behavior in all error scenarios on slave side #85

2024-10-24 20:01 UTC, huwzpf commented on cudampilib/cudampilib.c
> +    memcpy(sdata + sizeof(void *) + sizeof(cudaStream_t) + sizeof(int), src, count); // copy input data
Valid point, but I think this should be changed in all memcpy usages. Added issue for that #86

2024-10-24 20:03 UTC, merged